# Generated by Django 5.1.6 on 2025-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comments",
        ),
        migrations.AlterModelTable(
            name="project",
            table="projects",
        ),
        migrations.AlterModelTable(
            name="projectmember",
            table="project_members",
        ),
    ]
